main: server.alanbecker.net.Main
version: 1.0
api-version: 1.19
name: ABMCEnvoyBlocks
authors:
  - MasterGabeMOD
  - Akutasan
permissions:
  abmc.envoy.bypass:
    description: Allows bypassing block placement restrictions in the Envoy world.
    default: op